import type { Artwork, User } from "@/types"

export const sampleArtworks: Artwork[] = [
  {
    id: "1",
    title: "Sunset Dreams",
    artist: "Elena Rodriguez",
    description:
      "A vibrant oil painting capturing the essence of a Mediterranean sunset with warm oranges and deep purples.",
    price: 1200,
    category: "painting",
    images: ["/images/sunset-dreams.png"],
    inStock: true,
    stockQuantity: 1,
    dimensions: '24" x 36"',
    medium: "Oil on Canvas",
    year: 2023,
    featured: true,
    createdAt: "2023-01-15",
    updatedAt: "2023-01-15",
  },
  {
    id: "2",
    title: "Digital Cosmos",
    artist: "Alex Chen",
    description:
      "An abstract digital artwork exploring the intersection of technology and nature through algorithmic patterns.",
    price: 800,
    category: "digital",
    images: ["/images/digital-cosmos.png"],
    inStock: true,
    stockQuantity: 5,
    dimensions: "Digital - Various sizes available",
    medium: "Digital Art",
    year: 2024,
    featured: true,
    createdAt: "2024-02-10",
    updatedAt: "2024-02-10",
  },
  {
    id: "3",
    title: "Urban Reflections",
    artist: "Marcus Johnson",
    description:
      "A contemporary sculpture made from recycled materials, reflecting the beauty found in urban environments.",
    price: 2500,
    category: "sculpture",
    images: ["/images/urban-reflections.png"],
    inStock: true,
    stockQuantity: 1,
    dimensions: '18" x 12" x 8"',
    medium: "Mixed Media",
    year: 2023,
    featured: false,
    createdAt: "2023-06-20",
    updatedAt: "2023-06-20",
  },
  {
    id: "4",
    title: "Morning Light",
    artist: "Sarah Williams",
    description: "A serene landscape photograph capturing the first light of dawn over misty mountains.",
    price: 450,
    category: "photography",
    images: ["/images/morning-light.png"],
    inStock: true,
    stockQuantity: 10,
    dimensions: '16" x 20"',
    medium: "Fine Art Print",
    year: 2024,
    featured: true,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-05",
  },
  {
    id: "5",
    title: "Abstract Emotions",
    artist: "David Kim",
    description:
      "An expressive acrylic painting that explores human emotions through bold colors and dynamic brushstrokes.",
    price: 950,
    category: "painting",
    images: ["/images/abstract-emotions.png"],
    inStock: true,
    stockQuantity: 1,
    dimensions: '30" x 40"',
    medium: "Acrylic on Canvas",
    year: 2023,
    featured: false,
    createdAt: "2023-09-12",
    updatedAt: "2023-09-12",
  },
  {
    id: "6",
    title: "Neon Dreams",
    artist: "Luna Martinez",
    description: "A futuristic digital artwork featuring neon colors and cyberpunk aesthetics.",
    price: 650,
    category: "digital",
    images: ["/images/neon-dreams.png"],
    inStock: true,
    stockQuantity: 3,
    dimensions: "Digital - Various sizes available",
    medium: "Digital Art",
    year: 2024,
    featured: false,
    createdAt: "2024-03-08",
    updatedAt: "2024-03-08",
  },
]

export const sampleUsers: User[] = [
  {
    id: "1",
    email: "admin@artful.com",
    name: "Admin User",
    role: "admin",
    createdAt: "2023-01-01",
  },
  {
    id: "2",
    email: "customer@example.com",
    name: "John Doe",
    role: "customer",
    createdAt: "2023-02-15",
  },
]
